### ISSUE TITLE
Segfault on run in world.cpp

### ISSUE THREAD

**Issue by scivision** [msokalski/asciicker#9]
I have tried this with MinGW/MSYS2, Mac/Clang, Linux/GCC, Visual Studio and in all cases when running "game" executable I get a segfault in world.cpp on updating sprite. I am using SDL2 and X11 as appropriate. Is there a particular version of SDL, is GPM required?

**Comment by msokalski** [comment]
Probably... you're suffering from a different CWD than executable expects is it to be.Please post a stack trace or even better inspect if sprite pointers look valid.

**Comment by msokalski** [comment]
You may also check if running game_term (right in xterm or tty console or any vt emu) makes any difference. That would isolate opengl / sdl2 backend problems out.

**Comment by msokalski** [comment]
stale
